# -*- coding: utf-8 -*-
"""Salary_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSTPXfAl8npyYP8igG-mu5TWPzIgwWHm

# Random Forest Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""## Training the Random Forest Regression model on the whole dataset"""

from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(X,y)

"""## Predicting a new result"""

regressor.predict([[6.5]])

"""## Visualising the Random Forest Regression results (higher resolution)"""

X_grid=np.arange(X.min(),X.max(),0.01)
X_grid=X_grid.reshape(-1,1)
plt.scatter(X,y,color="red")
plt.plot(X_grid,regressor.predict(X_grid),color="blue")
plt.title("Salary vs level (RFR)")
plt.xlabel("Level")
plt.ylabel("Salary")
plt.show()